Repository treadpit/wx_calendar, pull requests merged in 2020-01, with the labels that each got.

#254 支持多种不同样式得待办事项标记
  src/component/calendar/func/todo.js
  src/component/calendar/index.wxml
Labels: enhancement

#256 fix: Uncaught (in promise) TypeError when switch week mode #255
  calendar/index.js
  src/component/calendar/func/week.js
Labels: fixed

#259 fix: incorrect calculation of dates in week mode #257
  calendar/index.js
  src/component/calendar/index.js
Labels: bug
